### ISSUE TITLE
转化出错-AttributeError: 'Namespace' object has no attribute 'select'

### ISSUE THREAD

**Issue by revolutionxuanbei** [boypt/vmess2json#10]
```
(test) type result | python vmess2json.py
Found 10 items.

1
2
3
4
5
6
>..（以上均正常显示）
Traceback (most recent call last):
  File "vmess2json.py", line 730, in <module>
    select_multiple(stdin_data)
  File "vmess2json.py", line 658, in select_multiple
    elif int(option.select) > -1:
AttributeError: 'Namespace' object has no attribute 'select'

```
result文件为
```
vmess://
x10
```

**Comment by boypt** [comment]
fixed in 3e9fdd2

**Comment by boypt** [comment]
似乎问题是你的终端比较特殊，脚本没兼容好。

使用stdin输入了订阅数据，在再次读取菜单的用户输入时候需要重新打开/dev/tty，目前脚本在linux环境下是正常的, 不知道其他平台兼容情况如何。

目前 401b556 改进了`--subscribe`参数，可以接受本地文件路径或者http的url。建议改成用`--subscribe vmesssubs.txt`方式使用。
