### ISSUE TITLE
Reading from subscribe, shows binascii.Error: Incorrect padding

### ISSUE THREAD

**Issue by jm0477** [boypt/vmess2json#5]
Reading from subscribe ...
Traceback (most recent call last):
  File "vmess2json.py", line 723, in <module>
    select_multiple(read_subscribe(option.subscribe))
  File "vmess2json.py", line 630, in read_subscribe
    return base64.b64decode(_subs).decode().splitlines()
  File "/usr/lib/python3.7/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

Could you help on this? is that my subscribe content issue or ? 
the subscribe url works well on v2ray gui subscription.

**Comment by jm0477** [comment]
Issue resolved by modifying the b64decode padding

**Comment by jm0477** [comment]
I forked and fixed with a pull request, please help to check if this needs to be merged.
it works for me.
